//! HMAC-SHA256 signing of ingest payloads.
//!
//! Canonical form signed:
//!   `{observer_id}\n{ts}\n{nonce}\n{body_sha256_hex}`
//!
//! Worker verifies: signature matches, |now - ts| < 10 min, nonce unseen.
//! This is intentionally minimalist — no TLS pinning, no rotating keys yet.
//! Secrets are per-observer, generated by the automation script.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};

type HmacSha256 = Hmac<Sha256>;

#[derive(Debug, thiserror::Error)]
pub enum HmacError {
    #[error("hmac: invalid key length")]
    InvalidKey,
}

pub fn body_digest_hex(body: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(body);
    hex::encode(hasher.finalize())
}

pub fn canonical_string(observer_id: &str, ts: &str, nonce: &str, body_sha: &str) -> String {
    format!("{observer_id}\n{ts}\n{nonce}\n{body_sha}")
}

pub fn sign(secret: &[u8], canonical: &str) -> Result<String, HmacError> {
    let mut mac = HmacSha256::new_from_slice(secret).map_err(|_| HmacError::InvalidKey)?;
    mac.update(canonical.as_bytes());
    Ok(hex::encode(mac.finalize().into_bytes()))
}

pub fn verify(secret: &[u8], canonical: &str, sig_hex: &str) -> bool {
    let Ok(mut mac) = HmacSha256::new_from_slice(secret) else {
        return false;
    };
    mac.update(canonical.as_bytes());
    let Ok(expected) = hex::decode(sig_hex) else {
        return false;
    };
    mac.verify_slice(&expected).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip() {
        let key = b"s3cret";
        let c = canonical_string("obs-1", "2026-04-20T00:00:00Z", "nonce-xyz", "deadbeef");
        let sig = sign(key, &c).unwrap();
        assert!(verify(key, &c, &sig));
        assert!(!verify(b"other", &c, &sig));
    }
}
